version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Mapeando a porta 80 do contêiner para a porta 8080 no host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs # Mapeia logs para uma pasta local, por exemplo
